### PR TITLE
Add Octave as a Calculator

### PR DESCRIPTION
**Pull request by prateek**
Add a Calculator Implementation for `octave`

### CODE REVIEW

**Comment by prateek** [comment]
Working prototype based on [JavaOctave](https://kenai.com/projects/javaoctave/pages/Home) - I put a fork on GH in case of anything [here](https://github.com/prateek/javaoctave). My biggest gripe with the implementation is auto-promotion of some types. The Octave library I'm using doesn't expose a Java layer for all Octave types, for numeric types it only exposes BoolMatrix, IntMatrix and DoubleMatrix. So I auto promote to those as needed.

**Comment by prateek** [comment]
Couple more things to point out: 
- I couldn't find a great way to identify return values from the execution of the Octave code. I didn't want to ask the user to specify the values explicitly, so I went with looking at the new variables created after the execution of the script and picking those as the return values. 
- Right now, only a single new variable is allowed. If the octave code creates more, I explicitly throw an exception because I wouldn't know which value to return. To return multiple values, I think we'd have to change the contract for Calculators to be `Function<Exhibit, Exhibit>` instead of `Function<Exhibit, Iterable<Obs>>`. IMO it'd be a useful change. What do you think?

**Comment by jwills** [comment]
Hey man-- these look cool. Could you rebase them into two commits: one to add the Vec stuff, and a second one to add the Octave prototype?

Re: the ExhibitCalculator, yeah, I think that's a good idea. I think it would give us more flexibility to return multiple values from a single environment, like in R or Octave where we can do a bunch of calculations and might want to do post-processing on any/all of them. The current Calculator interface works for SQL and other use cases where the return type is always something that is essentially a table, but we might want to rename it to something else.

**Comment by prateek** [comment]
Sure thing dude, the history on the branches is rebased/squashed.

Re: the ExhibitCalc: I'm not sure what the current Calculator return values would be migrated to - move from Iterable<Obs> to a "result" Frame in an Exhibit? As for the name, I'm partial to `Functor`, what say?

**Pull request merged**
